### ISSUE TITLE
Datasets used in experiments

### ISSUE THREAD

**Issue by tzc0029** [xyltt/LPT#2]
Thank you for sharing your work! Could you provide the datasets you used in the experiments?

Thanks!

**Comment by xyltt** [comment]
Hello!

The datasets used in the paper are all open-sourced.

**Comment by tzc0029** [comment]
Thank you. May I also ask what you did to the lm head in GPT2-large exp? Did you include the lm head in training or freeze it? Or do you happen to have some pre-trained weights for the lm head?

**Comment by xyltt** [comment]
The lm-head is frozen.
